/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_bridge;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class InterfazLogin extends javax.swing.JFrame {

    /**
     * Creates new form InterfazLogin
     */
    public InterfazLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelppal = new javax.swing.JPanel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelVersion = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAcceder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jLabelVersion1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú login");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 460));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_bridge/images/biblioteca.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 100));

        jPanelppal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelppal.setBorder(null);
        jPanelppal.setMaximumSize(new java.awt.Dimension(687, 468));
        jPanelppal.setMinimumSize(new java.awt.Dimension(687, 468));
        jPanelppal.setPreferredSize(new java.awt.Dimension(408, 233));
        jPanelppal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldUser.setBorder(null);
        jTextFieldUser.setMaximumSize(new java.awt.Dimension(40, 40));
        jTextFieldUser.setMinimumSize(new java.awt.Dimension(40, 16));
        jTextFieldUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUserMouseClicked(evt);
            }
        });
        jPanelppal.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 260, 30));

        jLabelVersion.setBackground(new java.awt.Color(0, 0, 0));
        jLabelVersion.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabelVersion.setText("Acceder");
        jLabelVersion.setBorder(null);
        jPanelppal.add(jLabelVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, -1));

        jButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalir.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setText("Salir");
        jButtonSalir.setBorder(null);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.setMaximumSize(new java.awt.Dimension(47, 25));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(47, 25));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(47, 25));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelppal.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 50));

        jButtonAcceder.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAcceder.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButtonAcceder.setText("Entrar");
        jButtonAcceder.setToolTipText("");
        jButtonAcceder.setActionCommand("Acceder");
        jButtonAcceder.setBorder(null);
        jButtonAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        jPanelppal.add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelppal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, 10));

        jPasswordFieldPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordFieldPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordFieldPass.setBorder(null);
        jPasswordFieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldPassMouseClicked(evt);
            }
        });
        jPasswordFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassActionPerformed(evt);
            }
        });
        jPasswordFieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPassKeyPressed(evt);
            }
        });
        jPanelppal.add(jPasswordFieldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 30));

        jLabelVersion1.setText("v 1.0.0");
        jPanelppal.add(jLabelVersion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 47, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanelppal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_bridge/images/usuario.png"))); // NOI18N
        jPanelppal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces_bridge/images/llavepng.png"))); // NOI18N
        jPanelppal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelppal, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelppal, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUserMouseClicked
        jTextFieldUser.setText("");
    }//GEN-LAST:event_jTextFieldUserMouseClicked

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Si pulsamos salir que se cierre la aplicacion

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
        if(jTextFieldUser.getText().toLowerCase().equals("admin") && (jPasswordFieldPass.getText().equals("1234"))){
            this.dispose();
            
            new MenuPrincipal().setVisible(true);
        }else{

            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos", "Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAccederActionPerformed

    private void jPasswordFieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldPassMouseClicked
        jPasswordFieldPass.setText("");
    }//GEN-LAST:event_jPasswordFieldPassMouseClicked

    private void jPasswordFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassActionPerformed

    private void jPasswordFieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPassKeyPressed
        //Implementamos esto para que cuando el usuario meta la pass dentro del
        //jtextfieldpass y pulse enter haga lo mismo que el jButton

    }//GEN-LAST:event_jPasswordFieldPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JLabel jLabelVersion1;
    private javax.swing.JPanel jPanelppal;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
